server:
  port: 8082
spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr:  127.0.0.1:8848 # 配置nacos 服务端地址
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nc_sys?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
logging:
  level:
    com.itheima: debug