server:
  port: 10010
spring:
  application:
    name: gateway-service
  cloud:
    #注册中心 相关配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置nacos 服务端地址
    #网关配置
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带cookie
            allow-credentials: true
            # 允许跨域的源(网站域名/ip)，设置*为全部
            allowed-origins:
            - "http://localhost:9530"
            - "http://127.0.0.1:9530"
            - "http://127.0.0.1"
            - "http://localhost"
            # 允许跨域请求里的head字段，设置*为全部
            allowed-headers: "*"
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowed-methods:
            - GET
            - POST
            - DELETE
            - PUT
            - OPTIONS
            # 跨域允许的有效期
            max-age: 3600
      routes:
      - id: search-service #微服务名称
        uri: lb://search-service
        predicates:     #predicates用于匹配HTTP请求的不同属性
        - Path=/search/** #匹配到的URL地址
        filters:
        - StripPrefix=0
        # 文档问服务
      - id: document-service #微服务名称
        uri: lb://document-service
        predicates:
        - Path=/document/**
        filters:
        - StripPrefix=0 #真实转发路径为 /document/xxx
        # 推送微服务
      - id: notify-service #微服务名称
        uri: lb://notify-service #即sys-service服务的负载均衡地址
        predicates:     #predicates用于匹配HTTP请求的不同属性
        - Path=/msg/** #匹配到的URL地址
        filters:
        - StripPrefix=1 #真实转发路径为 /xxx
      #系统服务
      - id: sys-service  #路由名称 该名称任意写
        uri: lb://sys-service #lb:load balacne 负载均衡
        predicates:
        - Path=/sys/**  #匹配路径规则  地址中包含/sys 请求会转发到系统微服务
        filters:
        - StripPrefix=1 #转发请求到目标微服务，1代表去除一位前缀  /** 会被转发到其他微服务
        # localhost：10010/sys/user      /user这部分转发目标微服务
      # 认证中心
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1
      # 认证微服务
      - id: auth-service #微服务名称
        uri: lb://auth-service #即auth-service服务的负载均衡地址
        predicates:     #predicates用于匹配HTTP请求的不同属性
        - Path=/auth/** #匹配到的URL地址
        filters:
        - StripPrefix=1 #在转发之前将/auth前缀去掉